version 2.4.0

diff --git a/main/backupmenu b/main/backupmenu
--- a/main/backupmenu
+++ b/main/backupmenu
@@ -1,26 +1,16 @@
 #!/bin/bash
-#==HEADER==
+# === HEADER ===
 # Name : backupmenu
 # Description:  Backup CLI for debian Linux based distro using cp, Tar and rsync.
 # Software : bash shell
 # Written : Gavin lyons 
 # Software repo URL : https://github.com/gavinlyonsrepo/backupmenu
 
-#==LIBRARY==
-#Source the bashmultitool  library 
-LIBPATH="/usr/lib/bashmultitool/"
-for MYFILE in "$LIBPATH"*;
-do
-	source "$MYFILE"
-done
-
 #==GLOBAL VARIABLES SETUP==
-#cyan bright prompt for select menus
+
+# 1. Prompt cyan bright prompt for select menus
 PS3="$(printf "\033[36;1m")By your command: $(printf "\033[0m") "
-
-# config file name
-CONFIG="backupmenu.cfg"
-
+# 2. Text editor
 # check if $EDITOR Environmental variable is set if not set it to nano
 # used for modifying config files
 if [ -z "${EDITOR}" ]
@@ -28,57 +18,54 @@ then
 	export EDITOR="nano"
 fi
 
-# Setup the Program Paths aka DESTx destiations 
-# DEST1-3 from $CONFIG, Dest4 misc, dest5 config file, dest6 readme,
-# dest7 library modules
-DEST5="$HOME/.config/backupmenu" # default path for config file
-DEST6="/usr/share/doc/backupmenu/" # readme
-DEST7="/usr/lib/backupmenu/modules/" #lib modules
+# 3. Config file name and path
+# shellcheck disable=SC2034
+CONFIG_FILE="backupmenu.cfg"
+CONFIG_FILE_PATH="$HOME/.config/backupmenu" # default path for config file
+mkdir -p "$CONFIG_FILE_PATH"
 
-#========================
-# *****NB  Devel path comment , OUT for production NB *****
-#DEST7="../modules/"  
-#========================
-
-mkdir -p "$DEST5"
-
-#==FUNCTIONS==
-#Source the module files for the functions from the backupmenu library folder
-#at /usr/lib/backupmenu/modules/* , Function syntax: nameFunc.
-for MYFILE in "$DEST7"*;
+# === LIBRARY ===
+#Source the bashmultitool library 
+BM_LIB_PATH="/usr/lib/bashmultitool/"
+if [ ! -d "$BM_LIB_PATH" ]
+then
+	echo "dependancy bashmultitool library not found at $BM_LIB_PATH, exiting."
+	echo "Please install bashmultitool library and try again."
+	echo "See readme for more information."
+	exit 1
+fi
+for MYFILE in "$BM_LIB_PATH"*;
 do
+	# shellcheck disable=SC1090
 	source "$MYFILE"
 done
 
-#==MAIN CODE==
+# === MODULES ===
+# Source the module files for the functions from the backupmenu library folder
+# at /usr/lib/backupmenu/modules/* , Function syntax: nameFunc.
+# Module path, development
+#BM_MOD_PATH="../modules/"
+# Module Path, production
+BM_MOD_PATH="/usr/lib/backupmenu/modules/" 
+for MYFILE in "$BM_MOD_PATH"*;
+do
+	# shellcheck disable=SC1090
+	source "$MYFILE"
+done
+
+# === MAIN CODE ===
 
 clear
 #Display opening screen title 
 bmtPromptFunc line "="  b_cyan
-
 bmtPrintFunc norm "Backup Utility Menu"
 bmtPrintFunc norm "$(date +%T" "%d-%a-Week%U-%b-%Y)"
 bmtPrintFunc norm "Unix epoch time $(date +%s)     "
-
-bmtLinuxFunc distrocheck
-	case $? in
-		4)
-			bmtPrintFunc  norm "$(dpkg -s backupmenu 2> /dev/null | grep Version)"
-		;;
-		5)
-			bmtPrintFunc norm "$(pacman -Qs backupmenu | head -1 | cut -c 7-20)"
-		;;
-		*)
-			bmtPrintFunc norm "Version 2.3"
-		;;
-	esac
-
+bmtPrintFunc norm "Version 2.4.0"
 bmtPromptFunc line "="  b_cyan
 
 while true; do
-	cd ~ || exitHandlerFunc DEST4
+	cd ~ || exitHandlerFunc "misc_dir_path"
 	DisplayFunc
 done
 
-
-#==END==
diff --git a/modules/miscModule b/modules/miscModule
--- a/modules/miscModule
+++ b/modules/miscModule
@@ -5,10 +5,10 @@
 # ReadmeFunc, readconfigFunc,  makeDirFunc
 
 
-#FUNCTION HEADER
+# FUNCTION HEADER
 # NAME :  exitHandlerFunc 
 # DESCRIPTION: error handler deal with user 
-#exits and path not found errors and internet failure 
+# exits and path not found errors and internet failure 
 # INPUTS:  $2  filename 
 # PROCESS : exitout DEST 1-6  file error
 # or bad argument option input
@@ -16,34 +16,36 @@ function exitHandlerFunc
 {
 	#double square brackets without use of quotes on matching pattern 
 	#for glob support
-	if [[ "$1" = DEST* ]]
+	if [[ "$1" = *dest* ]]
 	then
 		bmtPrintFunc red "Path not found to Destination directory"
 	fi
 	case "$1" in
 			exitout) : ;;
-			DEST1) bmtPrintFunc red "$DEST1" ;;
-			DEST2) bmtPrintFunc red "$DEST2" ;;
-			DEST3) bmtPrintFunc red "$DEST3" ;;
-			DEST4) bmtPrintFunc red "Path not found to directory" ;;
-			DEST5) bmtPrintFunc red "$DEST5" ;;
-			DEST6) bmtPrintFuncred  "$DEST6";;
-			README) bmtPrintFunc red "Missing Readme file";;
+			destination_path_1) bmtPrintFunc red "$BM_DEST_PATH_1" ;;
+			destination_path_2) bmtPrintFunc red "$BM_DEST_PATH_2" ;;
+			destination_path_3) bmtPrintFunc red "$BM_DEST_PATH_3" ;;
+			destination_path_4) bmtPrintFunc red "$BM_DEST_PATH_4" ;;
+			destination_path_5) bmtPrintFunc red "$BM_DEST_PATH_5" ;;
+			destination_path_6) bmtPrintFunc red "$BM_DEST_PATH_6" ;;
+			misc_dir_path) bmtPrintFunc red "Path not found to directory" ;;
+			CONFIG_FILE_PATH) bmtPrintFunc red "$CONFIG_FILE_PATH" ;;
+			Readme_Path) bmtPrintFuncred  "Missing readme path";;
+			Readme) bmtPrintFunc red "Missing Readme file";;
 			fileerror) bmtPrintFunc red "File error at :"
-			bmtPrintFunc red "$DEST5/$CONFIG"  ;;
+				bmtPrintFunc red "$CONFIG_FILE_PATH/$CONFIG" ;;
 			*) bmtPrintFunc yellow "Unknown input to error handler";;
-	 esac
+	esac
 	bmtPrintFunc b_yellow "Goodbye $USER!"
 	bmtPromptFunc anykey "and exit." b_green
 	if [ "$1" = "exitout" ]
 	then
-		#non-error exit
-		exit 0
+		exit 0 # non-error exit
 	fi 
 	exit 1
 }
 
-#FUNCTION HEADER
+# FUNCTION HEADER
 # NAME : DisplayFunc
 # DESCRIPTION : Function to display main menu
 function DisplayFunc
@@ -58,7 +60,7 @@ bmtPrintFunc b_cyan "Main Menu:"
 	select choiceMainVar in "${optionsMArr[@]}"
 	do
 	case "$choiceMainVar" in
-			"${optionsMArr[0]}")  #Full system backup
+			"${optionsMArr[0]}")  # Full system backup
 				clear
 				readconfigFunc
 				bmtPromptFunc anykey "" b_green
@@ -71,15 +73,15 @@ bmtPrintFunc b_cyan "Main Menu:"
 				bmtPromptFunc anykey "" b_green
 			;;
 			
-			"${optionsMArr[2]}")  #config file edit or view
+			"${optionsMArr[2]}")  # config file edit or view
 				readconfigFunc "USERCALL"
 			;;
 			
-			"${optionsMArr[3]}")  #Display Readme
+			"${optionsMArr[3]}")  # Display Readme
 				ReadmeFunc
 			;;
 			
-			"${optionsMArr[4]}")  #rsync
+			"${optionsMArr[4]}")  # rsync
 				clear
 				readconfigFunc
 				bmtPromptFunc anykey "" b_green
@@ -88,7 +90,7 @@ bmtPrintFunc b_cyan "Main Menu:"
 				exitHandlerFunc exitout
 			;;
 			
-			*)#exit
+			*) # exit
 				exitHandlerFunc exitout 
 			;;
 	esac
@@ -97,14 +99,15 @@ bmtPrintFunc b_cyan "Main Menu:"
 
 }
 
-#FUNCTION HEADER
+# FUNCTION HEADER
 # NAME : ReadmeFunc
 # DESCRIPTION : Displays Readme to screen 
 function ReadmeFunc
 {
+	local Readme_Path="/usr/share/doc/backupmenu/" # readme
 	bmtPromptFunc line "="  b_cyan
-	bmtPrintFunc  b_green "Displaying backupmenu README.md file at $DEST6"
-	cd "$DEST6"  || exitHandlerFunc DEST6
+	bmtPrintFunc  b_green "Displaying backupmenu README.md file at $Readme_Path"
+	cd "$Readme_Path"  || exitHandlerFunc "Readme_path"
 	if [ -f README.md.gz  ]
 	then
 		zless README.md.gz 
@@ -112,41 +115,41 @@ function ReadmeFunc
 	then
 		less README.md
 	else 
-		exitHandlerFunc README
+		exitHandlerFunc "Readme"
 	fi
 	bmtPrintFunc  b_green "Done!" 
 	bmtPromptFunc line "="  b_cyan
 	bmtPromptFunc anykey "" b_green
 }
 
-#FUNCTION HEADER
+# FUNCTION HEADER
 # NAME : readconfigFunc
 # DESCRIPTION:read the config file into program 
 # passed USERCALL
 # INPUTS $1 USERCALL when called by user
 # OUTPUTS : sets paths for backup function 
-# PROCESS : read $DEST5/$CONFIG
+# PROCESS : read $CONFIG_FILE_PATH/$CONFIG
 function readconfigFunc
 {
-	#check input if called by user from menu or option
+	# check input if called by user from menu or option
 	if [ "$1" = "USERCALL" ]
 		then
-		cd "$DEST5"  || exitHandlerFunc DEST5
-		if [ -f "$DEST5/$CONFIG" ] 
+		cd "$CONFIG_FILE_PATH"  || exitHandlerFunc CONFIG_FILE_PATH
+		if [ -f "$CONFIG_FILE_PATH/$CONFIG_FILE" ] 
 			then
 				local choiceCCVar
 				bmtPrintFunc  b_green "Do you want to edit or view? [e/V]"
 				read -r choiceCCVar
 				if [ "$choiceCCVar" = "e" ]
 					then
-						$EDITOR "$DEST5/$CONFIG" || exitHandlerFunc fileerror "$DEST5/$CONFIG"
+						$EDITOR "$CONFIG_FILE_PATH/$CONFIG_FILE" || exitHandlerFunc fileerror "$CONFIG_FILE_PATH/$CONFIG"
 						clear
 						bmtPrintFunc  b_green "Exiting config file edit option"
 						bmtPromptFunc anykey "and exit backupmenu." b_green
 						exit 0
 					else
 						bmtPrintFunc  b_green  "Custom paths read from file"
-						cat "$DEST5/$CONFIG" || exitHandlerFunc fileerror "$DEST5/$CONFIG"
+						cat "$CONFIG_FILE_PATH/$CONFIG_FILE" || exitHandlerFunc fileerror "$CONFIG_FILE_PATH/$CONFIG"
 						bmtPrintFunc  b_green "Done!"
 						bmtPromptFunc anykey "" b_green
 						return
@@ -156,42 +159,42 @@ function readconfigFunc
 		fi
 	fi
 	
-	#read $CONFIG for system back up paths 
-	bmtPrintFunc  b_green "Reading config file $CONFIG at:-"
-	bmtPrintFunc norm "$DEST5"
+	# read $CONFIG for system back up paths 
+	bmtPrintFunc  b_green "Reading config file $CONFIG_FILE at:-"
+	bmtPrintFunc norm "$CONFIG_FILE_PATH"
 	bmtPrintFunc norm " "
-	cd "$DEST5"  || exitHandlerFunc DEST5
-	#check if file there if not use defaults.
-	if [ ! -f "$DEST5/$CONFIG" ]
+	cd "$CONFIG_FILE_PATH"  || exitHandlerFunc CONFIG_FILE_PATH
+	# check if file there if not use defaults.
+	if [ ! -f "$CONFIG_FILE_PATH/$CONFIG_FILE" ]
 		then
 			makeConfigFunc
 		return
 	fi
-	# shellcheck disable=SC1091
-	source "$CONFIG" || exitHandlerFunc fileerror "$DEST5/$CONFIG"
+	# shellcheck disable=SC1090
+	source "$CONFIG_FILE" || exitHandlerFunc fileerror "$CONFIG_FILE_PATH/$CONFIG_FILE"
 	bmtPrintFunc  b_green  "Custom paths read from file"
 	bmtPrintFunc norm " "
-	cat "$CONFIG" || exitHandlerFunc fileerror "$DEST5/$CONFIG"
+	cat "$CONFIG_FILE" || exitHandlerFunc fileerror "$CONFIG_FILE_PATH/$CONFIG_FILE"
 	bmtPrintFunc norm " "
 	bmtPrintFunc  b_green "Done!"
 }
 
 
-#FUNCTION HEADER
+# FUNCTION HEADER
 # NAME : makeDirFunc
 # DESCRIPTION :  makes a directory with time/date stamp and enters it
-#Directory used for program output and backups. 
+# Directory used for program output and backups. 
 function makeDirFunc
 {
 	local dirVar=""
 	dirVar=$(date  +%d%b%y-%H%M)"$1"
 	mkdir "$dirVar"
-	cd "$dirVar" || exitHandlerFunc DEST4
+	cd "$dirVar" || exitHandlerFunc misc_dir_path
 	bmtPrintFunc norm "Directory for output made at:-"
 	pwd	 
 }
 
-#FUNCTION HEADER
+# FUNCTION HEADER
 # NAME : makeConfigFunc
 # DESCRIPTION :  If the config file does not exist provides a option 
 # to get a dummy default  from github with curl command.
@@ -201,14 +204,24 @@ function makeConfigFunc
 	bmtPrintFunc norm "Do u want to fetch the dummy default file with curl from github? [y/N]"
 	bmtPromptFunc yesno yes # y/N
 	case $? in
-		0)  #yes
+		0)  # yes
+			# check if curl is installed?
+			bmtLinuxFunc checkpac "curl" 2
+			if [ $? -ne 0 ]
+			then
+				bmtPrintFunc red "curl"
+				bmtPrintFunc yellow "curl is not installed, please install and try again."
+				exitHandlerFunc exitout
+			else
+				bmtPrintFunc b_green "curl is installed, proceeding with fetching config file from github."
+			fi
 			curl -o backupmenu.cfg  https://raw.githubusercontent.com/gavinlyonsrepo/backupmenu/master/documentation/backupmenu.cfg
-			bmtPrintFunc norm "backupmenu.cfg downloaded from github."
+			bmtPrintFunc norm "backupmenu.cfg downloaded from github with curl"
 			bmtPrintFunc norm "Please Restart."
 			exitHandlerFunc  exitout
 		;;
-		2) #no
-			exitHandlerFunc fileerror "$DEST5/$CONFIG"
+		2) # no
+			exitHandlerFunc fileerror "$CONFIG_FILE_PATH/$CONFIG_FILE"
 		;;
 	esac
 }
